/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bileshganguly.tools.mgmt.societymanagementsystem.view;

import com.bileshganguly.tools.mgmt.societymanagementsystem.config.ManageConfig;
import com.bileshganguly.tools.mgmt.societymanagementsystem.dao.impl.ChargeTypeDaoImpl;
import com.bileshganguly.tools.mgmt.societymanagementsystem.model.ChargeType;
import com.bileshganguly.tools.mgmt.societymanagementsystem.model.Configuration;
import com.bileshganguly.tools.mgmt.societymanagementsystem.model.Flat;
import com.bileshganguly.tools.mgmt.societymanagementsystem.sql.DatabaseConnection;
import com.bileshganguly.tools.mgmt.societymanagementsystem.util.AmountInWords;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextPane;

/**
 *
 * @author bilesh
 */
public class BillFrame extends javax.swing.JFrame {

    private List<ChargeType> chargeTypes = new LinkedList<>();
    private final Map<String, Double> manualRecords = new HashMap<>();

    private Configuration configuration;
    private final Flat flat;

    private String today;

    private final String monthYear;
    private final boolean isTenant;
    private final boolean isReceipt;
    
    private final int parkingSlots;
    
    private JPanel container;
    private JPanel topContainer;
    private JLabel lableBill;
    private JButton addButton;
    private JButton printButton;
    private JButton removeAllButton;

    /**
     * Creates new form BillFrame
     *
     * @param flat
     * @param monthYear
     * @param isTenant
     * @param isReceipt
     * @param parkingSlots
     */
    public BillFrame(Flat flat, String monthYear, boolean isTenant, boolean isReceipt, int parkingSlots) {
        this.flat = flat;
        this.monthYear = monthYear;
        this.isTenant = isTenant;
        this.isReceipt = isReceipt;
        this.parkingSlots = parkingSlots;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Receipt");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BillFrame(null, null, false, false, 0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private String billHTML() {
        StringBuilder sb = new StringBuilder();
        sb.append("<html>"
                + "<style type='text/css'>"
                + "body, h1, th, td {"
                + "  font-family: Serif;"
                + "  font-size: 8pt;"
                + "  line-height: 1em;"
                + "}"
                + "#firstHeading {"
                + "  font-size: 12pt;"
                + "  font-weight: bold;"
                + "  line-height: 1.15em;"
                + "}"
                + "#secondHeading {"
                + "  font-size: 10pt;"
                + "  font-weight: bold;"
                + "  line-height: 1.15em;"
                + "}"
                + "th {"
                + "  border-bottom: thin solid gray;"
                + "}"
                + ".overline td {"
                + "  border-top: thin solid gray;"
                + "}"
                + "</style>"
                + "<body>");
        sb.append("<p id='firstHeading' align='center'>" + configuration.getBuildingName() + "</p><hr width=80% />"
                + "<p id='secondHeading' align='center'>" + configuration.getBuildingAddress() + "</p>"
                + "<p id='secondHeading' align='center'>Reg. No.: " + configuration.getBuildingRegNo() + "</p>"
                + "<br/>"
                + "<p align='right'>Date: " + today + "</p><br/>"
                + "<p>To,</p>"
                + "<p>&nbsp;&nbsp;" + flat.getName() + "</p><br/>"
                + "<p>&nbsp;&nbsp;" + (isReceipt ? "Receipt" : "Bill") + " for Society Charges for the month of \"" + monthYear + "\" for Flat No \"" + flat.getFlatNumber() + "\"</p>"
                + "<br/>");

        sb.append("<table width='450' cellspacing='0' cellpadding='2'>"
                + "<tr>"
                + "<th width='10%' align='center'>Sr. No.</th>"
                + "<th></th>"
                + "<th width='50%' align='left'>Particulars</th>"
                + "<th width='40%' align='right'>Amount (Rs.)</th>"
                + "</tr>");
        int count = 1;
        for (ChargeType cType : chargeTypes) {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append(cType.getTypeName())
                    .append("</td>"
                            + "<td align='right'>")
                    .append("-")
                    .append("</td>"
                            + "</tr>");
        }
        
        // For Fixed Rate
        boolean isFixed = true;
        if(isFixed) {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Fixed Charges (Rs." + configuration.getFixedRate() + " per sq. ft.)")
                    .append("</td>"
                            + "<td align='right'>")
                    .append(formatDouble(calculateFixed()))
                    .append("</td>"
                            + "</tr>");
        } else {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Fixed Charges")
                    .append("</td>"
                            + "<td align='right'>")
                    .append("-")
                    .append("</td>"
                            + "</tr>");
        }
        
        // For tenant rate
        if(isTenant) {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Tenant Charges (Rs." + configuration.getTenantRate() + " per sq. ft.)")
                    .append("</td>"
                            + "<td align='right'>")
                    .append(formatDouble(calculateTenant()))
                    .append("</td>"
                            + "</tr>");
        } else {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Tenant Charges")
                    .append("</td>"
                            + "<td align='right'>")
                    .append("-")
                    .append("</td>"
                            + "</tr>");
        }
        
        // For parking slots
        if(parkingSlots > 0) {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Parking Charges (Rs." + configuration.getParkingAmount()+ " per parking slot)")
                    .append("</td>"
                            + "<td align='right'>")
                    .append(formatDouble(calculateParking()))
                    .append("</td>"
                            + "</tr>");
        } else {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append("Parking Charges")
                    .append("</td>"
                            + "<td align='right'>")
                    .append("-")
                    .append("</td>"
                            + "</tr>");
        }
        
        // Manual Records
        for(Entry<String, Double> entry : manualRecords.entrySet()) {
            sb.append("<tr>"
                    + "<td align='right'>")
                    .append(count++)
                    .append("</td><td></td>"
                            + "<td>")
                    .append(entry.getKey())
                    .append("</td>"
                            + "<td align='right'>")
                    .append(formatDouble(entry.getValue()))
                    .append("</td>"
                            + "</tr>");
        }
        
        sb.append("<tr class='overline'>"
                + "<td>&nbsp;")
                .append("</td><td></td>"
                        + "<td align='right'>")
                .append("Grand Total")
                .append("</td>"
                        + "<td align='right'>")
                .append(formatAmount(calculate()))
                .append("</td>"
                        + "</tr>"
                        + "</table>");
        sb.append("<br/>Amount in words: Rupees " + AmountInWords.convert((int) calculate()) + " Only<br/>"
                + "<br/><p>Thanking you,</p><br/>"
                + "<p>For<p><br/>"
                + "<p>" + configuration.getBuildingName() + "</p><br/>"
                + "<p>This is a computer generated " + (isReceipt ? "Receipt" : "Bill") + " which needs no signature.</p>");

        return sb.toString();
    }

    private String formatDouble(double amount) {
        String pattern = "##,##,##,###.00";
        DecimalFormat myFormatter = new DecimalFormat(pattern);
        return myFormatter.format(amount);
        //return new MessageFormat("{0,number}").format(new Object[]{amount});
    }

    private String formatAmount(double amount) {
        String pattern = "\u20B9##,##,##,###.00";
        DecimalFormat myFormatter = new DecimalFormat(pattern);
        return myFormatter.format(amount);
        //return new MessageFormat("Rs.{0,number}").format(new Object[]{amount});
    }

    private void init() {
        ManageConfig manageConfig = new ManageConfig();
        configuration = manageConfig.getConfiguration();

        DatabaseConnection databaseConnection = new DatabaseConnection();
        if (databaseConnection.connect()) {
            ChargeTypeDaoImpl dbChargeType = new ChargeTypeDaoImpl(databaseConnection);
            chargeTypes = dbChargeType.getAll();
        }

        Date dNow = new Date();
        SimpleDateFormat ft
                = new SimpleDateFormat("dd/MM/yyyy");

        today = ft.format(dNow);

        this.getContentPane().setBackground(Color.WHITE);
        this.getContentPane().setLayout(new BorderLayout());

        topContainer = new JPanel(); 
        topContainer.setBorder(BorderFactory.createEmptyBorder());
        topContainer.setBackground(Color.WHITE);
        topContainer.setLayout(new FlowLayout());
        
        addButton = new JButton("Add");
        addButton.addActionListener((ActionEvent e) -> {
            this.remove(container);
            addRecords();
            lableBill.invalidate();
            lableBill.setText(billHTML());
        });
        topContainer.add(addButton); 
        
        removeAllButton = new JButton("Remove Manual Records");
        removeAllButton.addActionListener((ActionEvent e) -> {
            this.remove(container);
            manualRecords.clear();
            lableBill.invalidate();
            lableBill.setText(billHTML());
        });
        topContainer.add(removeAllButton); 
        
        printButton = new JButton("Print");
        printButton.addActionListener((ActionEvent e) -> {
            print();
        });
        topContainer.add(printButton);
        
        this.add(topContainer, BorderLayout.PAGE_START);
        
        container = new JPanel(); 
        container.setBorder(BorderFactory.createEmptyBorder());
        container.setBackground(Color.WHITE);
        container.setLayout(new FlowLayout());

        lableBill = new JLabel(billHTML());
        lableBill.setBorder(BorderFactory.createEmptyBorder());
        container.add(lableBill);
        
        this.add(container, BorderLayout.CENTER);
    }
    
    private void addRecords() {
        //System.out.println("Record Added");
        
        String particulars = JOptionPane.showInputDialog("Particulars");
        try {
            double amount = Double.parseDouble(JOptionPane.showInputDialog("Amount"));
            manualRecords.put(particulars, amount);
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Please enter only numbers in amount.", JOptionPane.ERROR_MESSAGE);
        }

    }

    private double calculate() {   
        double sum = 0;
        sum = calculateFixed() + calculateTenant() + calculateParking();
        sum = manualRecords.entrySet().stream().map((entry) -> entry.getValue()).reduce(sum, (accumulator, _item) -> accumulator + _item);
        return sum;
    }
    
    private double calculateFixed() {
        double rate = configuration.getFixedRate();
        
        return flat.getArea() * rate;
    }
    
    private double calculateTenant() {
        double rate = configuration.getTenantRate();
        
        return isTenant ? flat.getArea() * rate : 0;
    }
    
    private double calculateParking() {
        double rate = configuration.getParkingAmount();
        
        return parkingSlots * rate;
    }

    private void print() {
        try {
            JTextPane jtp = new JTextPane();
            jtp.setContentType("text/html");
            jtp.setText(billHTML());
            jtp.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Printing Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
