/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bileshganguly.tools.mgmt.societymanagementsystem.view;

import com.bileshganguly.tools.mgmt.societymanagementsystem.dao.impl.ChargeTypeDaoImpl;
import com.bileshganguly.tools.mgmt.societymanagementsystem.model.ChargeType;
import com.bileshganguly.tools.mgmt.societymanagementsystem.sql.DatabaseConnection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author bilesh
 */
public class ChargeTypeFrame extends JFrame {
    private final MainFrame parent; 

    private DatabaseConnection databaseConnection;
    private ChargeTypeDaoImpl dbChargeType;

    private final String[] fieldList = new String[]{"ID", "Name", "Description", "Amount"};

    private List<ChargeType> chargeTypes = new LinkedList<>();
    private ChargeTypeModel dataModel;

    /**
     * Creates new form ChargeTypeFrame
     */
    public ChargeTypeFrame() {
        this.parent = null;
        initComponents();
        init();
    }
    
    public ChargeTypeFrame(MainFrame parent) {
        this.parent = parent;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        txtAmt = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Charge Types");

        labelName.setText("Name");

        labelDescription.setText("Description");

        labelAmount.setText("Amount");

        txtId.setEditable(false);

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            null,
            fieldList
        ));
        jScrollPane1.setViewportView(tblView);

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        labelId.setText("ID");

        btClear.setText("Clear");
        btClear.setToolTipText("");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelDescription)
                            .addComponent(labelId)
                            .addComponent(labelAmount))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(labelId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelete)
                    .addComponent(labelDescription)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAmount)
                    .addComponent(btClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (validateFields()) {
            ChargeType chargeType = new ChargeType();
            chargeType.setTypeName(txtName.getText());
            chargeType.setTypeDesc(txtDesc.getText());
            chargeType.setAmount(Double.parseDouble(txtAmt.getText()));
            if (dbChargeType.insert(chargeType)) {
                chargeTypes.add(chargeType);
                clear();
                refreshTable();
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please check the values in the fields."
                    + "\nNone of the fields can be empty."
                    + "\nThe amount field only takes numbers.",
                    "Invalid Value in fields", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if (validateFields()) {
            ChargeType chargeType = new ChargeType();
            chargeType.setTypeId(Integer.parseInt(txtId.getText()));
            chargeType.setTypeName(txtName.getText());
            chargeType.setTypeDesc(txtDesc.getText());
            chargeType.setAmount(Double.parseDouble(txtAmt.getText()));
            if (dbChargeType.update(chargeType)) {
                int idx = tblView.getSelectedRow();
                chargeTypes.set(idx, chargeType);
                clear();
                refreshTable();
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please check the values in the fields."
                    + "\nNone of the fields can be empty."
                    + "\nThe amount field only takes numbers.",
                    "Invalid Value in fields", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        clear();
    }//GEN-LAST:event_btClearActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        if (tblView.getSelectedRow() >= 0 && !txtId.getText().isEmpty()) {
            ChargeType chargeType = new ChargeType();
            chargeType.setTypeId(Integer.parseInt(txtId.getText()));
            chargeType.setTypeName(txtName.getText());
            chargeType.setTypeDesc(txtDesc.getText());
            chargeType.setAmount(Double.parseDouble(txtAmt.getText()));
            if (dbChargeType.delete(chargeType)) {
                int idx = tblView.getSelectedRow();
                chargeTypes.remove(idx);
                clear();
                refreshTable();
            }
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChargeTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChargeTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChargeTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChargeTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChargeTypeFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelName;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private class ChargeTypeModel extends AbstractTableModel {

        private final List<ChargeType> contents;
        private final String[] columns;

        public ChargeTypeModel(List<ChargeType> contents, String[] columns) {
            this.contents = contents;
            this.columns = columns;
        }

        @Override
        public String getColumnName(int column) {
            return columns[column];
        }

        @Override
        public int getRowCount() {
            return this.contents.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return Integer.class;
                case 3:
                    return Double.class;
                default:
                    return String.class;
            }
        }

        @Override
        public Object getValueAt(int row, int column) {
            ChargeType chargeType = contents.get(row);

            switch (column) {
                case 0:
                    return chargeType.getTypeId();
                case 1:
                    return chargeType.getTypeName();
                case 2:
                    return chargeType.getTypeDesc();
                case 3:
                    return chargeType.getAmount();
                default:
                    return "N/A";
            }
        }

    }

    private boolean validateFields() {
        return validateEmpty() && validateDouble();
    }

    private boolean validateEmpty() {
        return !txtName.getText().isEmpty()
                && !txtDesc.getText().isEmpty()
                && !txtAmt.getText().isEmpty();
    }

    private boolean validateDouble() {
        try {
            double d = Double.parseDouble(txtAmt.getText());
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    private void init() {
        databaseConnection = new DatabaseConnection();
        if (databaseConnection.connect()) {
            dbChargeType = new ChargeTypeDaoImpl(databaseConnection);
            populateList();
        }

        tblView.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (e.getValueIsAdjusting()) {
                return;
            }

            final DefaultListSelectionModel target = (DefaultListSelectionModel) e.getSource();
            int isSelectedIndex = target.getAnchorSelectionIndex();

            setFields(isSelectedIndex);
        });

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                databaseConnection.disconnect();
                if(parent != null) parent.setEnabled(true);
            }
        });
    }

    private void clear() {
        tblView.clearSelection();

        txtAmt.setText("");
        txtDesc.setText("");
        txtId.setText("");
        txtName.setText("");
    }

    private void setFields(int idx) {
        if (idx >= 0 && idx < chargeTypes.size()) {
            ChargeType chargeType = chargeTypes.get(idx);

            txtAmt.setText(String.format("%.2f", chargeType.getAmount()));
            txtDesc.setText(chargeType.getTypeDesc());
            txtId.setText(Integer.toString(chargeType.getTypeId()));
            txtName.setText(chargeType.getTypeName());
        }
    }

    private void populateList() {
        chargeTypes = dbChargeType.getAll();
        dataModel = new ChargeTypeModel(chargeTypes, fieldList);
        tblView.setModel(dataModel);
    }

    private void refreshTable() {
        dataModel.fireTableDataChanged();
    }
}
